# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flower < Formula
  desc ""
  homepage "https://github.com/KaueSabinoSRV17/Flower"
  version "1.3.8"

  on_macos do
    url "https://github.com/KaueSabinoSRV17/Flower/releases/download/1.3.8/Flower_1.3.8_darwin_all.tar.gz"
    sha256 "4f7ede948ae02ca603d68652690bd3877028c55b736f419482530b904eedd177"

    def install
      bin.install "Flower"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/KaueSabinoSRV17/Flower/releases/download/1.3.8/Flower_1.3.8_linux_amd64.tar.gz"
      sha256 "2d55f9140ffde924cd4588e9ac59e8bcac1d11ba5c0908dddf25a0c4fddb329d"

      def install
        bin.install "flow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KaueSabinoSRV17/Flower/releases/download/1.3.8/Flower_1.3.8_linux_arm64.tar.gz"
      sha256 "5007aa0119821a6273cac709eda909c2da449cdcec962fb8ff5e4375febe975e"

      def install
        bin.install "flow"
      end
    end
  end
end
