# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flower < Formula
  desc ""
  homepage "https://github.com/KaueSabinoSRV17/Flower"
  version "1.0.5"

  on_macos do
    url "https://github.com/KaueSabinoSRV17/Flower/releases/download/1.0.5/Flower_1.0.5_darwin_all.tar.gz"
    sha256 "6d681e3d13639f5c7a50479113a3e1ec8f4ca230c652bce2656ed5902d853274"

    def install
      bin.install "Flower"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KaueSabinoSRV17/Flower/releases/download/1.0.5/Flower_1.0.5_linux_arm64.tar.gz"
      sha256 "390543bc9b1f63a15439e3cc548494a7f04a8625d122fc2f754eb0bceb501526"

      def install
        bin.install "flow"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KaueSabinoSRV17/Flower/releases/download/1.0.5/Flower_1.0.5_linux_amd64.tar.gz"
      sha256 "831754eb421083c8bb52a4f9efd7c33f093e99aaed23eede2c578d00194ed243"

      def install
        bin.install "flow"
      end
    end
  end
end
