# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flower < Formula
  desc ""
  homepage "https://github.com/KaueSabinoSRV17/Flower"
  version "1.0.2"

  on_macos do
    url "https://github.com/KaueSabinoSRV17/Flower/releases/download/1.0.2/Flower_1.0.2_darwin_all.tar.gz"
    sha256 "6b3e51cd249ef6d0fb0bbe9adef2d35f83e7721846f0eeb06f2fa2a762ae1bbb"

    def install
      bin.install "Flower"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KaueSabinoSRV17/Flower/releases/download/1.0.2/Flower_1.0.2_linux_arm64.tar.gz"
      sha256 "63c7f4e00611834b2c7184f084ae0c624161e7c07299686350aa357e8a9ec216"

      def install
        bin.install "flow"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KaueSabinoSRV17/Flower/releases/download/1.0.2/Flower_1.0.2_linux_amd64.tar.gz"
      sha256 "dcd5155e2f55c891325ba04ffc67e7e1d5c56a1bf3a2faaea061e23bbce6f045"

      def install
        bin.install "flow"
      end
    end
  end
end
